version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}equipmentmanagementwebapi
    build:
      context: .
      dockerfile: src/EquipmentManagement.WebApi/Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    ports:
      - 8080:8080