version: '3.4'

services:
  equipmentmanagement.webapi:
    image: ${DOCKER_REGISTRY-}equipmentmanagementwebapi
    build:
      context: .
      dockerfile: src/EquipmentManagement.WebApi/Dockerfile
