version: '3.4'

services:
  webapi:
    image: equipment-management:1.0.0
    build:
      context: .
      dockerfile: src/EquipmentManagement.WebApi/Dockerfile
    restart: on-failure
    depends_on:
      - db
    volumes:
      - images:/app/images/
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__SecretKey: ${JWT_SECRETKEY}
      Jwt__TokenLifetimeMinutes: ${JWT_LIFETIME}
      AdminUsername: ${ADMIN_USERNAME}
      AdminPassword: ${ADMIN_PASSWORD}
      ConnectionStrings__Data: ${APP_DATA}
      ConnectionStrings__Users: ${AUTH_DATA}
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
    - data:/var/lib/postgresql/data
  adminer:
    image: adminer
    

volumes:
  images:
  data:  