version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}equipmentmanagementwebapi
    build:
      context: .
      dockerfile: src/EquipmentManagement.WebApi/Dockerfile
    depends_on:
      - db
    ports:
      - 5134:80

  #ui:
    #image: ${DOCKER_REGISTRY-}equipmentmanagementui
    #build:
      #context: .
      #dockerfile: ui/EquipmentManagement.UI/Dockerfile
    #depends_on:
      #- webapi
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example