version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}equipmentmanagementwebapi
    build:
      context: .
      dockerfile: src/EquipmentManagement.WebApi/Dockerfile
    depends_on:
      - db
  ui:
    image: ${DOCKER_REGISTRY-}equipmentmanagementui
    build:
      context: .
      dockerfile: ui/EquipmentManagement.UI/Dockerfile
    depends_on:
      - webapi
    ports:
      - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
