// <auto-generated />
using System;
using EquipmentManagement.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentManagement.Auth.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20230327094343_UpdatedPassword")]
    partial class UpdatedPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentManagement.Application.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15ab498b-2a34-41fc-964e-6d047c6f17ec"),
                            Login = "Admin",
                            PasswordHash = "GxMmSBwf3vwp0jXcF9OQO6lJXtkDuCbWfteejKDjZhTNTyotEgxswiquvORSYk04",
                            PasswordSalt = "HxfQhcWMJFaASfzS+h5qvg==",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
